export const EventRecordErrorCode = {
  INVALID_DECISION_ID: 'INVALID_DECISION_ID',
  DECISION_SUBJECT_MISMATCH: 'DECISION_SUBJECT_MISMATCH',
  UNKNOWN_EVENT_TYPE: 'UNKNOWN_EVENT_TYPE',
  EVENT_TYPE_ARCHIVED: 'EVENT_TYPE_ARCHIVED',
  INVALID_EVENT_PAYLOAD: 'INVALID_EVENT_PAYLOAD',
  QUEUE_UNAVAILABLE: 'QUEUE_UNAVAILABLE',
  EVENT_TYPE_CATALOG_NOT_READY: 'EVENT_TYPE_CATALOG_NOT_READY',
  BATCH_TOO_LARGE: 'BATCH_TOO_LARGE',
} as const;
export type EventRecordErrorCode = (typeof EventRecordErrorCode)[keyof typeof EventRecordErrorCode];
