export enum DecisionReason {
  FLAG_DEFAULT = 'FLAG_DEFAULT',
  EXPERIMENT_ASSIGNED = 'EXPERIMENT_ASSIGNED',
  TARGETING_NOT_MATCHED = 'TARGETING_NOT_MATCHED',
  NOT_IN_AUDIENCE = 'NOT_IN_AUDIENCE',
  PARTICIPATION_LIMIT_EXCEEDED = 'PARTICIPATION_LIMIT_EXCEEDED',
  EXPERIMENT_PAUSED = 'EXPERIMENT_PAUSED',
  EXPERIMENT_CONFLICT = 'EXPERIMENT_CONFLICT',
  SNAPSHOT_NOT_READY = 'SNAPSHOT_NOT_READY',
  STATE_CONFLICT_RETRY_EXCEEDED = 'STATE_CONFLICT_RETRY_EXCEEDED',
  RUNTIME_DEGRADED_FAIL_CLOSED = 'RUNTIME_DEGRADED_FAIL_CLOSED',
}
